-- Step 1
CREATE DATABASE IF NOT EXISTS DEV_DB;

-- Step 2
USE DATABASE DEV_DB;

-- Step 3
CREATE SCHEMA IF NOT EXISTS PUBLIC;

-- Step 4
USE SCHEMA PUBLIC;

-- Step 5
CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
