name: Snowflake Deployment

on:
  push:
    branches:
      - uat
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.32-linux_x86_64.bash
          bash snowsql-1.2.32-linux_x86_64.bash

      - name: Deploy SQL files
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          snowsql -a $SNOWSQL_ACCOUNT \
                   -u $SNOWSQL_USER \
                   -r $SNOWSQL_ROLE \
                   -w $SNOWSQL_WAREHOUSE \
                   -f snowflake/dev/ddl/V1_0_0__create_customer_table.sql
